server:
  port: 8888
  address: 0.0.0.0
  servlet:
    context-path: /web

# 开发时，禁止缓存，方便常看页面更新
# https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/howto.html#howto-hotswapping
spring.thymeleaf.cache: false

logging.level:
  icu.kyakya.orm.mybatis.mapper: debug
  web: debug

spring:
  mvc:
    throwExceptionIfNoHandlerFound: true # if page not found, it will throw error, and then ControllerAdvice will catch the error.
  main:
    allow-bean-definition-overriding: true
  web:
    locale: zh   # 默认使用
