group: icu.kyakya.orm.mybatis

spring:
  config:
    activate.on-profile: generator
mybatis:
  generator:
    moduleName: orm.mybatis
    modelTargetPackage: ${group}.domain
    clientTargetPackage: ${group}.mapper
    tables: users   # Separated by comma`,`
