spring:
  profiles.active: develop

---

# https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-use-yaml-for-external-properties
spring:
  config:
    activate.on-profile: develop
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: user
    password: userpass
    driver-class-name: com.mysql.jdbc.Driver

---
spring:
  config:
    activate.on-profile: prod
  datasource:
    url: jdbc:mysql://localhost/test
    username: dbuser
    password: dbpass
    driver-class-name: com.mysql.jdbc.Driver

---
spring:
  config:
    activate.on-profile: generator
mybatis:
  generator:
    modelTargetPackage: icu.kyakya.orm.mybatis.domain
    clientTargetPackage: icu.kyakya.orm.mybatis.mapper