spring:
  profiles.active: develop
group: icu.kyakya.orm.mybatis

---

# https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-use-yaml-for-external-properties
spring:
  config:
    activate.on-profile: develop
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: user
    password: userpass
    driver-class-name: com.mysql.jdbc.Driver

---
spring:
  config:
    activate.on-profile: prod # todo demo
  datasource:
    url: jdbc:mysql://localhost/test
    username: dbuser
    password: dbpass
    driver-class-name: com.mysql.jdbc.Driver

---
spring:
  config:
    activate.on-profile: generator
mybatis:
  generator:
    modelTargetPackage: ${group}.domain
    clientTargetPackage: ${group}.mapper
#    tables: user,city   # 默认情况下，是创建所有非系统的表格对应的Mapper，如需单独制定时，可以使用该字段