# https://www.baeldung.com/spring-data-jpa-generate-db-schema
# create SQL script by Java code.
spring.jpa.properties:
  javax.persistence.schema-generation:
    scripts:
      action: create
      create-source: metadata
      create-target: create.sql